name: unit_tests

on:
  push:
  pull_request:
  workflow_dispatch:

  # Run automatically every monday
  schedule:
    - cron: 1 12 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'

    name: test (${{ matrix.python-version }})
    steps:
    - uses: actions/checkout@v1
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pdm install
    - name: Run tests
      run: pdm run test
